### ISSUE TITLE
Add sourcemaps?

### ISSUE THREAD

**Issue by sunnysingh** [axa-ch/metalsmith-postcss#6]
I don't think there's a way for me to enable sourcemaps through this plugin's options, so is it possible for you to add sourcemap support?

**Comment by davidknezic** [comment]
Sure, that's possible!

Did some research and it's pretty common that every metalsmith plugin does that on its own. Nothing like `gulp-sourcemaps` available for metalsmith plugins.

That's why I'll try to make the [postcss sourcemap](https://github.com/postcss/postcss#source-map) options available over the next days/weeks.

**Comment by sunnysingh** [comment]
@davidknezic Awesome! I'm messing around with PostCSS for my personal site revamp and it would be nice to have sourcemaps.

**Comment by sventschui** [comment]
Published 3.1.0 with basic sourcemaps support. Big thanks to @davidknezic. Sorry for the delay.  Let us know if you miss something
